"""
Setup Wizard — GUI-based first-time configuration for SharePoint Chatbot.

Guides employees through:
1. Entering company credentials (or using pre-filled defaults)
2. Validating the configuration
3. Running OAuth login (browser-based)
4. Confirming everything works

Run:  python setup_wizard.py
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import threading
import tkinter as tk
from tkinter import messagebox, ttk
from pathlib import Path

BASE_DIR = Path(__file__).parent
ENV_FILE = BASE_DIR / ".env"
ENV_EXAMPLE = BASE_DIR / ".env.example"
TOKEN_CACHE = BASE_DIR / ".token_cache.json"
VENV_DIR = BASE_DIR / "venv"
PYTHON_EXE = VENV_DIR / "Scripts" / "python.exe"

# ── Default company config (pre-filled by IT admin before distribution) ─
# These are read from .env.example or overridden here for bundled installs.
COMPANY_DEFAULTS: dict[str, str] = {}


def _load_defaults() -> dict[str, str]:
    """Load defaults from .env.example if it exists."""
    defaults = dict(COMPANY_DEFAULTS)
    if ENV_EXAMPLE.exists():
        for line in ENV_EXAMPLE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip()
                if value and not value.startswith("your-"):
                    defaults[key] = value
    return defaults


def _load_existing_env() -> dict[str, str]:
    """Load values from existing .env file."""
    values: dict[str, str] = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip()
    return values


def _write_env(values: dict[str, str]) -> None:
    """Write configuration to .env file."""
    lines = [
        "# SharePoint Chatbot Configuration",
        "# Auto-generated by setup wizard",
        "",
        "# -- Azure AD / SharePoint ------------------------------------------",
        f"AZURE_CLIENT_ID={values.get('AZURE_CLIENT_ID', '')}",
        f"AZURE_CLIENT_SECRET={values.get('AZURE_CLIENT_SECRET', '')}",
        f"AZURE_TENANT_ID={values.get('AZURE_TENANT_ID', '')}",
        "",
        f"SHAREPOINT_HOSTNAME={values.get('SHAREPOINT_HOSTNAME', '')}",
        f"SHAREPOINT_SITE_PATH={values.get('SHAREPOINT_SITE_PATH', '')}",
        f"SHAREPOINT_FOLDER={values.get('SHAREPOINT_FOLDER', '')}",
        "",
        "# -- NVIDIA API -----------------------------------------------------",
        f"NVIDIA_API_KEY={values.get('NVIDIA_API_KEY', '')}",
        f"NVIDIA_MODEL={values.get('NVIDIA_MODEL', 'meta/llama-3.3-70b-instruct')}",
        f"NVIDIA_VISION_MODEL={values.get('NVIDIA_VISION_MODEL', 'microsoft/phi-3.5-vision-instruct')}",
        "",
        "# -- RAG tuning (optional) ------------------------------------------",
        f"TOP_K_CHUNKS={values.get('TOP_K_CHUNKS', '5')}",
        f"MAX_FILE_SIZE_MB={values.get('MAX_FILE_SIZE_MB', '10')}",
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


class SetupWizard:
    """Tkinter-based setup wizard with multi-step flow."""

    def __init__(self) -> None:
        self.root = tk.Tk()
        self.root.title("SharePoint Chatbot — Setup")
        self.root.geometry("620x520")
        self.root.resizable(False, False)
        self.root.configure(bg="#f0f4f8")

        # Center the window
        self.root.update_idletasks()
        x = (self.root.winfo_screenwidth() - 620) // 2
        y = (self.root.winfo_screenheight() - 520) // 2
        self.root.geometry(f"+{x}+{y}")

        self.defaults = _load_defaults()
        self.existing = _load_existing_env()
        self.entries: dict[str, tk.Entry] = {}
        self.current_step = 0

        # Style
        style = ttk.Style()
        style.configure("Title.TLabel", font=("Segoe UI", 16, "bold"), background="#f0f4f8")
        style.configure("Subtitle.TLabel", font=("Segoe UI", 10), background="#f0f4f8", foreground="#555")
        style.configure("Step.TLabel", font=("Segoe UI", 9), background="#f0f4f8", foreground="#888")
        style.configure("Big.TButton", font=("Segoe UI", 11), padding=10)

        self._build_header()
        self._build_content_area()
        self._show_welcome()

    def _build_header(self) -> None:
        header = tk.Frame(self.root, bg="#0078d4", height=60)
        header.pack(fill="x")
        header.pack_propagate(False)

        tk.Label(
            header,
            text="  SharePoint Chatbot Setup",
            font=("Segoe UI", 14, "bold"),
            fg="white",
            bg="#0078d4",
            anchor="w",
        ).pack(fill="x", padx=16, pady=16)

    def _build_content_area(self) -> None:
        self.content = tk.Frame(self.root, bg="#f0f4f8")
        self.content.pack(fill="both", expand=True, padx=24, pady=16)

    def _clear_content(self) -> None:
        for widget in self.content.winfo_children():
            widget.destroy()

    # ── Step 1: Welcome ─────────────────────────────────────────────

    def _show_welcome(self) -> None:
        self._clear_content()
        self.current_step = 0

        ttk.Label(
            self.content,
            text="Welcome!",
            style="Title.TLabel",
        ).pack(anchor="w", pady=(8, 4))

        ttk.Label(
            self.content,
            text="This wizard will set up the SharePoint Chatbot on your computer.",
            style="Subtitle.TLabel",
            wraplength=560,
        ).pack(anchor="w", pady=(0, 16))

        info_frame = tk.Frame(self.content, bg="white", relief="groove", bd=1)
        info_frame.pack(fill="x", pady=8)

        steps = [
            "1.  Check Python & install dependencies",
            "2.  Configure connection settings",
            "3.  Sign in with your Office 365 account",
            "4.  Verify everything works",
        ]
        for step_text in steps:
            tk.Label(
                info_frame,
                text=step_text,
                font=("Segoe UI", 10),
                bg="white",
                anchor="w",
            ).pack(fill="x", padx=16, pady=4)

        # Spacer
        tk.Frame(info_frame, bg="white", height=8).pack()

        # Status checks
        status_frame = tk.Frame(self.content, bg="#f0f4f8")
        status_frame.pack(fill="x", pady=16)

        python_ok = self._check_python()
        venv_ok = VENV_DIR.exists()
        env_ok = ENV_FILE.exists() and not self._env_has_placeholders()
        token_ok = TOKEN_CACHE.exists()

        checks = [
            ("Python installed", python_ok),
            ("Virtual environment", venv_ok),
            ("Configuration (.env)", env_ok),
            ("Signed in", token_ok),
        ]
        for label, ok in checks:
            icon = "✅" if ok else "⬜"
            tk.Label(
                status_frame,
                text=f"  {icon}  {label}",
                font=("Segoe UI", 10),
                bg="#f0f4f8",
                anchor="w",
            ).pack(fill="x", pady=2)

        btn_frame = tk.Frame(self.content, bg="#f0f4f8")
        btn_frame.pack(fill="x", pady=16)

        ttk.Button(
            btn_frame,
            text="Start Setup →",
            style="Big.TButton",
            command=self._step_install_deps,
        ).pack(side="right")

    # ── Step 2: Install Dependencies ────────────────────────────────

    def _step_install_deps(self) -> None:
        self._clear_content()
        self.current_step = 1

        ttk.Label(
            self.content,
            text="Step 1 of 4 — Installing Dependencies",
            style="Title.TLabel",
        ).pack(anchor="w", pady=(8, 4))

        self.status_label = ttk.Label(
            self.content,
            text="Checking Python...",
            style="Subtitle.TLabel",
        )
        self.status_label.pack(anchor="w", pady=(0, 12))

        self.progress = ttk.Progressbar(
            self.content,
            mode="indeterminate",
            length=560,
        )
        self.progress.pack(fill="x", pady=8)
        self.progress.start(15)

        self.log_text = tk.Text(
            self.content,
            height=12,
            font=("Consolas", 9),
            bg="#1e1e1e",
            fg="#d4d4d4",
            state="disabled",
            wrap="word",
        )
        self.log_text.pack(fill="both", expand=True, pady=8)

        threading.Thread(target=self._do_install, daemon=True).start()

    def _log(self, msg: str) -> None:
        def _update():
            self.log_text.configure(state="normal")
            self.log_text.insert("end", msg + "\n")
            self.log_text.see("end")
            self.log_text.configure(state="disabled")
        self.root.after(0, _update)

    def _set_status(self, msg: str) -> None:
        self.root.after(0, lambda: self.status_label.configure(text=msg))

    def _do_install(self) -> None:
        try:
            # Check Python
            self._set_status("Checking Python installation...")
            result = subprocess.run(
                [sys.executable, "--version"],
                capture_output=True,
                text=True,
            )
            self._log(f"Python: {result.stdout.strip()}")

            # Create venv
            if not VENV_DIR.exists():
                self._set_status("Creating virtual environment...")
                self._log("Creating virtual environment...")
                subprocess.run(
                    [sys.executable, "-m", "venv", str(VENV_DIR)],
                    capture_output=True,
                    text=True,
                    check=True,
                )
                self._log("Virtual environment created.")
            else:
                self._log("Virtual environment already exists.")

            # Install dependencies
            self._set_status("Installing packages (this may take a few minutes)...")
            self._log("Installing dependencies from requirements.txt...")
            pip_exe = str(VENV_DIR / "Scripts" / "pip.exe")
            result = subprocess.run(
                [pip_exe, "install", "--upgrade", "pip"],
                capture_output=True,
                text=True,
                cwd=str(BASE_DIR),
            )
            result = subprocess.run(
                [pip_exe, "install", "-r", str(BASE_DIR / "requirements.txt")],
                capture_output=True,
                text=True,
                cwd=str(BASE_DIR),
            )
            if result.returncode != 0:
                self._log(f"ERROR: {result.stderr}")
                self._set_status("Installation failed! Check the log below.")
                self.root.after(0, lambda: self.progress.stop())
                return

            self._log("All dependencies installed successfully.")
            self._set_status("Dependencies installed!")
            self.root.after(0, lambda: self.progress.stop())
            self.root.after(0, self._install_done)

        except Exception as exc:
            self._log(f"ERROR: {exc}")
            self._set_status("Installation failed!")
            self.root.after(0, lambda: self.progress.stop())

    def _install_done(self) -> None:
        self.progress.pack_forget()

        btn_frame = tk.Frame(self.content, bg="#f0f4f8")
        btn_frame.pack(fill="x", pady=8)

        ttk.Button(
            btn_frame,
            text="Next → Configure",
            style="Big.TButton",
            command=self._step_configure,
        ).pack(side="right")

    # ── Step 3: Configuration ───────────────────────────────────────

    def _step_configure(self) -> None:
        self._clear_content()
        self.current_step = 2

        ttk.Label(
            self.content,
            text="Step 2 of 4 — Configuration",
            style="Title.TLabel",
        ).pack(anchor="w", pady=(8, 4))

        # If company defaults cover all required fields, show simplified view
        required_keys = [
            "AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID",
            "SHAREPOINT_HOSTNAME", "NVIDIA_API_KEY",
        ]
        merged = {**self.defaults, **self.existing}
        all_prefilled = all(
            merged.get(k) and not merged.get(k, "").startswith("your-")
            for k in required_keys
        )

        if all_prefilled:
            ttk.Label(
                self.content,
                text="Configuration is already set up by your IT admin.\n"
                     "You can review or change settings below, or just click Next.",
                style="Subtitle.TLabel",
                wraplength=560,
            ).pack(anchor="w", pady=(0, 12))
        else:
            ttk.Label(
                self.content,
                text="Enter the connection details provided by your IT admin.\n"
                     "Fields marked with * are required.",
                style="Subtitle.TLabel",
                wraplength=560,
            ).pack(anchor="w", pady=(0, 12))

        # Scrollable form
        canvas = tk.Canvas(self.content, bg="#f0f4f8", highlightthickness=0)
        scrollbar = ttk.Scrollbar(self.content, orient="vertical", command=canvas.yview)
        form_frame = tk.Frame(canvas, bg="#f0f4f8")

        form_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all")),
        )
        canvas.create_window((0, 0), window=form_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)

        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

        fields = [
            ("AZURE_CLIENT_ID", "Azure Client ID *", False),
            ("AZURE_CLIENT_SECRET", "Azure Client Secret *", True),
            ("AZURE_TENANT_ID", "Azure Tenant ID *", False),
            ("SHAREPOINT_HOSTNAME", "SharePoint Hostname *", False),
            ("SHAREPOINT_SITE_PATH", "Site Path (e.g. sites/yoursite)", False),
            ("SHAREPOINT_FOLDER", "Folder Path (optional)", False),
            ("NVIDIA_API_KEY", "NVIDIA API Key *", True),
        ]

        self.entries = {}
        for key, label, is_secret in fields:
            tk.Label(
                form_frame,
                text=label,
                font=("Segoe UI", 9),
                bg="#f0f4f8",
                anchor="w",
            ).pack(fill="x", pady=(8, 2))

            entry = tk.Entry(
                form_frame,
                font=("Consolas", 10),
                show="•" if is_secret else "",
                width=60,
            )
            # Pre-fill: prefer existing .env, then defaults
            prefill = merged.get(key, "")
            if prefill and not prefill.startswith("your-"):
                entry.insert(0, prefill)
            entry.pack(fill="x", pady=(0, 4))
            self.entries[key] = entry

        btn_frame = tk.Frame(self.content, bg="#f0f4f8")
        btn_frame.pack(fill="x", pady=(12, 0))

        ttk.Button(
            btn_frame,
            text="← Back",
            command=self._show_welcome,
        ).pack(side="left")

        ttk.Button(
            btn_frame,
            text="Save & Sign In →",
            style="Big.TButton",
            command=self._save_and_login,
        ).pack(side="right")

    def _save_and_login(self) -> None:
        # Validate required fields
        required = ["AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID",
                     "SHAREPOINT_HOSTNAME", "NVIDIA_API_KEY"]
        values: dict[str, str] = {}
        for key, entry in self.entries.items():
            values[key] = entry.get().strip()

        # Include non-editable defaults
        for key in ["NVIDIA_MODEL", "NVIDIA_VISION_MODEL", "TOP_K_CHUNKS", "MAX_FILE_SIZE_MB"]:
            if key not in values:
                merged = {**self.defaults, **self.existing}
                values[key] = merged.get(key, "")

        missing = [k for k in required if not values.get(k)]
        if missing:
            messagebox.showerror(
                "Missing Fields",
                f"Please fill in all required fields:\n\n" +
                "\n".join(f"  • {k}" for k in missing),
            )
            return

        # Write .env
        _write_env(values)
        self._step_login()

    # ── Step 4: OAuth Login ─────────────────────────────────────────

    def _step_login(self) -> None:
        self._clear_content()
        self.current_step = 3

        ttk.Label(
            self.content,
            text="Step 3 of 4 — Sign In",
            style="Title.TLabel",
        ).pack(anchor="w", pady=(8, 4))

        ttk.Label(
            self.content,
            text="A browser window will open. Sign in with your Office 365 email.\n"
                 "After signing in, close the browser tab and come back here.",
            style="Subtitle.TLabel",
            wraplength=560,
        ).pack(anchor="w", pady=(0, 16))

        self.login_status = ttk.Label(
            self.content,
            text="Starting sign-in...",
            style="Subtitle.TLabel",
        )
        self.login_status.pack(anchor="w", pady=8)

        self.login_progress = ttk.Progressbar(
            self.content,
            mode="indeterminate",
            length=560,
        )
        self.login_progress.pack(fill="x", pady=8)
        self.login_progress.start(15)

        self.login_log = tk.Text(
            self.content,
            height=10,
            font=("Consolas", 9),
            bg="#1e1e1e",
            fg="#d4d4d4",
            state="disabled",
            wrap="word",
        )
        self.login_log.pack(fill="both", expand=True, pady=8)

        threading.Thread(target=self._do_login, daemon=True).start()

    def _login_log(self, msg: str) -> None:
        def _update():
            self.login_log.configure(state="normal")
            self.login_log.insert("end", msg + "\n")
            self.login_log.see("end")
            self.login_log.configure(state="disabled")
        self.root.after(0, _update)

    def _do_login(self) -> None:
        try:
            python = str(PYTHON_EXE) if PYTHON_EXE.exists() else sys.executable
            self._login_log(f"Running: {python} login.py")
            self.root.after(0, lambda: self.login_status.configure(
                text="Waiting for browser sign-in..."
            ))

            result = subprocess.run(
                [python, str(BASE_DIR / "login.py")],
                capture_output=True,
                text=True,
                cwd=str(BASE_DIR),
                timeout=180,
            )

            for line in result.stdout.splitlines():
                stripped = line.strip()
                if stripped:
                    self._login_log(stripped)

            if result.returncode == 0 and TOKEN_CACHE.exists():
                self._login_log("Sign-in successful!")
                self.root.after(0, lambda: self.login_status.configure(
                    text="Sign-in successful!"
                ))
                self.root.after(0, lambda: self.login_progress.stop())
                self.root.after(500, self._login_done)
            else:
                if result.stderr:
                    self._login_log(f"Error: {result.stderr.strip()}")
                self.root.after(0, lambda: self.login_status.configure(
                    text="Sign-in may have failed. You can retry."
                ))
                self.root.after(0, lambda: self.login_progress.stop())
                self.root.after(0, self._login_retry_buttons)

        except subprocess.TimeoutExpired:
            self._login_log("Timed out waiting for sign-in.")
            self.root.after(0, lambda: self.login_status.configure(
                text="Sign-in timed out. Click Retry to try again."
            ))
            self.root.after(0, lambda: self.login_progress.stop())
            self.root.after(0, self._login_retry_buttons)
        except Exception as exc:
            self._login_log(f"Error: {exc}")
            self.root.after(0, lambda: self.login_progress.stop())

    def _login_retry_buttons(self) -> None:
        btn_frame = tk.Frame(self.content, bg="#f0f4f8")
        btn_frame.pack(fill="x", pady=8)

        ttk.Button(
            btn_frame,
            text="Retry Sign-In",
            style="Big.TButton",
            command=self._step_login,
        ).pack(side="left", padx=(0, 8))

        ttk.Button(
            btn_frame,
            text="Skip (sign in later)",
            command=self._step_complete,
        ).pack(side="left")

    def _login_done(self) -> None:
        self.login_progress.pack_forget()

        btn_frame = tk.Frame(self.content, bg="#f0f4f8")
        btn_frame.pack(fill="x", pady=8)

        ttk.Button(
            btn_frame,
            text="Next → Finish",
            style="Big.TButton",
            command=self._step_complete,
        ).pack(side="right")

    # ── Step 5: Complete ────────────────────────────────────────────

    def _step_complete(self) -> None:
        self._clear_content()
        self.current_step = 4

        ttk.Label(
            self.content,
            text="Step 4 of 4 — Setup Complete!",
            style="Title.TLabel",
        ).pack(anchor="w", pady=(8, 4))

        token_ok = TOKEN_CACHE.exists()
        status_text = (
            "Everything is set up and ready to go!"
            if token_ok
            else "Setup is complete, but you still need to sign in.\n"
                 "Run start.bat — it will prompt you to sign in on first launch."
        )
        ttk.Label(
            self.content,
            text=status_text,
            style="Subtitle.TLabel",
            wraplength=560,
        ).pack(anchor="w", pady=(0, 16))

        # Summary box
        summary = tk.Frame(self.content, bg="white", relief="groove", bd=1)
        summary.pack(fill="x", pady=8)

        tk.Label(
            summary,
            text="What's next:",
            font=("Segoe UI", 11, "bold"),
            bg="white",
            anchor="w",
        ).pack(fill="x", padx=16, pady=(12, 4))

        next_steps = [
            "• Double-click start.bat to launch the chatbot",
            "• Your browser will open to http://127.0.0.1:8000",
            "• Click 'Index' to scan your SharePoint documents",
            "• Start asking questions about your documents!",
        ]
        for text in next_steps:
            tk.Label(
                summary,
                text=text,
                font=("Segoe UI", 10),
                bg="white",
                anchor="w",
            ).pack(fill="x", padx=16, pady=2)

        tk.Frame(summary, bg="white", height=12).pack()

        # Desktop shortcut offer
        shortcut_frame = tk.Frame(self.content, bg="#f0f4f8")
        shortcut_frame.pack(fill="x", pady=12)

        self.create_shortcut_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(
            shortcut_frame,
            text="Create desktop shortcut",
            variable=self.create_shortcut_var,
        ).pack(anchor="w")

        # Buttons
        btn_frame = tk.Frame(self.content, bg="#f0f4f8")
        btn_frame.pack(fill="x", pady=16)

        ttk.Button(
            btn_frame,
            text="Launch Chatbot Now",
            style="Big.TButton",
            command=self._finish_and_launch,
        ).pack(side="right", padx=(8, 0))

        ttk.Button(
            btn_frame,
            text="Close",
            command=self._finish,
        ).pack(side="right")

    def _finish(self) -> None:
        if self.create_shortcut_var.get():
            self._create_desktop_shortcut()
        self.root.destroy()

    def _finish_and_launch(self) -> None:
        if self.create_shortcut_var.get():
            self._create_desktop_shortcut()
        # Launch start.bat detached
        subprocess.Popen(
            ["cmd", "/c", "start", "", str(BASE_DIR / "start.bat")],
            cwd=str(BASE_DIR),
        )
        self.root.destroy()

    # ── Utilities ───────────────────────────────────────────────────

    def _check_python(self) -> bool:
        try:
            result = subprocess.run(
                [sys.executable, "--version"],
                capture_output=True,
                text=True,
            )
            return result.returncode == 0
        except Exception:
            return False

    def _env_has_placeholders(self) -> bool:
        if not ENV_FILE.exists():
            return True
        content = ENV_FILE.read_text(encoding="utf-8")
        return "your-" in content

    def _create_desktop_shortcut(self) -> None:
        """Create a Windows shortcut (.lnk) on the desktop."""
        try:
            desktop = Path.home() / "Desktop"
            if not desktop.exists():
                return

            shortcut_path = desktop / "SharePoint Chatbot.lnk"
            target = str(BASE_DIR / "start.bat")
            icon_path = str(BASE_DIR / "start.bat")
            working_dir = str(BASE_DIR)

            # Use PowerShell to create shortcut
            ps_script = (
                f'$ws = New-Object -ComObject WScript.Shell; '
                f'$s = $ws.CreateShortcut("{shortcut_path}"); '
                f'$s.TargetPath = "{target}"; '
                f'$s.WorkingDirectory = "{working_dir}"; '
                f'$s.Description = "SharePoint Chatbot"; '
                f'$s.Save()'
            )
            subprocess.run(
                ["powershell", "-Command", ps_script],
                capture_output=True,
                timeout=10,
            )
        except Exception:
            pass  # Non-critical — skip silently

    def run(self) -> None:
        self.root.mainloop()


def main() -> None:
    wizard = SetupWizard()
    wizard.run()


if __name__ == "__main__":
    main()
